
const GARDEN_MESSAGES_CN = [
  "指尖滑过空气，仿佛唤醒了沉睡的星尘。",
  "每一朵绽放的花，都是大地对天空的深情告白。",
  "这里的色彩，像是打翻了上帝的调色盘。",
  "光影交织间，万物生长的声音如诗般动听。",
  "你种下的不仅是种子，更是对美好生活的期许。",
  "微风在花瓣间穿行，带走了最后一丝冬日的寒意。",
  "这里的花朵似乎在窃窃私语，讨论着明天的露水。",
  "在这个数字角落，我看见了生命最原始的律动。",
  "阳光亲吻着幼苗，每一寸生机都显得格外珍贵。",
  "繁花簇拥间，现实与虚幻的界限悄然模糊。",
  "听，那是种子破土而出时给世界的惊喜。",
  "花开无声，却在空气中留下了最迷人的芬芳。",
  "你的手心似乎藏着春天的密码。",
  "这里的每一株草木，都记得你温柔的凝望。",
  "月光如果落在这里，也会被花香浸透。",
  "在喧嚣的世界里，这片小小的花园是心灵的避风港。",
  "每一片叶子的脉络，都写满了自然的神奇。",
  "你是这片微型宇宙的造物主，让色彩在此起舞。",
  "花瓣上的光晕，是数字化身对自然的致敬。",
  "这里的春天永不落幕，只要你还在播种希望。",
  "星辰坠入凡间，化作了这些五彩斑斓的生灵。",
  "指尖的温度，是花朵生长最渴望的源泉。",
  "每一朵花的盛开，都是一次跨越维度的奇迹。",
  "这是属于你的秘密森林，藏着风的呼吸。",
  "蝴蝶若能飞进这里，一定也会迷失在芬芳里。",
  "你创造的不仅是景观，更是一段静谧的时光。",
  "这里的绿色有种治愈的力量，能抚平一切褶皱。",
  "每一颗种子落地的瞬间，都是一颗梦想的诞生。",
  "花开半夏，情深几许，这花园懂你的每一个微笑。",
  "在这些线条与色彩中，我读出了生命的韧性。",
  "清晨的阳光洒向花心，那是自然最温柔的唤醒。",
  "你的指尖魔法，让钢筋水泥也开出了温柔。",
  "这里的生命如此轻盈，仿佛随时会化作流光。",
  "每一瓣花朵，都承载着关于美好的奇思妙想。",
  "愿这片花园的宁静，能长久驻留在你的心底。",
  "风吹过，那些花儿便跳起了只有你能看懂的舞。",
  "在这里，每一秒钟都有新的故事在悄悄发芽。",
  "这片色彩的海洋，是你送给这个世界最美的礼物。",
  "看那含苞待放的姿态，充满了对未知的渴望。",
  "这里的花朵从不凋零，因为它们生长在你的爱里。",
  "每一缕香气，都是数字灵魂对真实的渴望。",
  "在这个奇幻的空间，你是唯一的调色师。",
  "生命之火在此点燃，映照出你专注的双眸。",
  "这不仅是花园，更是你内心深处的一片净土。",
  "看，那些花朵正在努力向着你所在的方向生长。",
  "每一个像素的律动，都在致敬自然的鬼斧神工。",
  "这里的世界很小，却能容纳你所有的温柔。",
  "花开一瞬，即是永恒，在这片代码的海洋中。",
  "你是这片生机的引路人，带它们领略这人间烟火。",
  "愿这片繁花，能照亮你每一个疲惫的瞬间。",
  "每一根嫩芽，都在用力诉说着生存的喜悦。",
  "这里的云朵似乎也沾染了花香的味道。",
  "你用想象力灌溉，收获了这一地烂漫。",
  "在这个静谧的时刻，连空气都变得甜美起来。",
  "万物皆有灵性，尤其是这些由你亲手种下的花。",
  "色彩的和谐，是这片花园最动听的旋律。",
  "每一朵花都有它的性格，或张扬或腼腆。",
  "在这里，时间仿佛静止，唯有生机在流转。",
  "你的每一次轻触，都是对大地的深情抚摸。",
  "这里的景色，比梦境更加真实而动人。",
  "愿你的生活也能如这花园般，常开常新。",
  "这是科技与自然最美的邂逅。",
  "每一道光线的折射，都在为你的作品加冕。",
  "这里藏着无数个春天，等着你去一一发现。",
  "你的创意让这片虚无，焕发出了绚丽的彩虹。",
  "看那些花瓣的质感，仿佛真实触手可及。",
  "这里的生机，是代码世界里最温暖的奇迹。",
  "每一颗种子，都怀揣着成为森林的梦想。",
  "你的专注，让这些花朵开出了最自信的模样。",
  "这片色彩的派对，你是唯一的邀请嘉宾。",
  "愿这花园的芬芳，能带走你所有的忧虑。",
  "生命最美的样子，莫过于在此刻自由绽放。",
  "这里的每一寸空间，都充满了探索的趣味。",
  "你是这片幻境的守护者，看护着每一丝萌芽。",
  "每一次花开，都是一次关于美的深刻讨论。",
  "在这片由你定义的重力下，花朵开出了自由。",
  "这里没有严寒，只有属于你的永恒暖春。",
  "每一朵花的姿态，都像是你性格的一个切面。",
  "看，连光影都在追逐你指尖留下的余温。",
  "这里的自然，是人类智慧与情感的结晶。",
  "每一个转瞬即逝的瞬间，都值得被温柔对待。",
  "愿这片绚烂，能成为你创作灵感的源泉。",
  "在这里，你可以是任何人，只要你愿意播种。",
  "花朵的呼吸，是这个空间里最轻柔的背景音。",
  "你的笑容，是这片花园最好的肥料。",
  "看那万紫千红，皆是你意志的体现。",
  "每一瓣色彩的叠加，都成就了一场视觉盛宴。",
  "这花园里的每一滴露水，都映照着你的影子。",
  "愿这份静谧，能伴你度过每一个宁静的夜晚。",
  "这里的生命虽简，却有着惊心动魄的美感。",
  "你在这里画下的每一个圈，都成了一个微型世界。",
  "花瓣的低吟，是写给这个时代的一首情歌。",
  "在这里，我们重新定义了‘生长’的意义。",
  "愿这片花园，能成为你心中永恒的风景。",
  "每一道曲线，都是自然律动在数字世界的投射。",
  "这里的芬芳虽不可闻，却能沁入你的灵魂。",
  "你看那花开，像不像你第一次心动的模样？",
  "在这个平行的时空，花朵代表着最纯粹的希望。",
  "愿这片缤纷，能为你平凡的日子增添一抹亮色。",
  "最后，请记住这片花园，它是你创造的奇迹。"
];

const GARDEN_MESSAGES_EN = [
  "Fingertips glide through the air, awakening sleeping stardust.",
  "Every blooming flower is a profound confession from Earth to the sky.",
  "The colors here look like God's spilled palette.",
  "The sound of growth in the play of light is as beautiful as poetry.",
  "You plant not just seeds, but expectations for a beautiful life.",
  "A breeze weaves through petals, taking the last chill of winter away.",
  "The flowers seem to be whispering about tomorrow's dew.",
  "In this digital corner, I see the most primal rhythm of life.",
  "Sunlight kisses the seedlings; every inch of vitality is precious.",
  "Among the flowers, the line between reality and illusion blurs.",
  "Listen, that's the surprise the seeds give to the world as they burst.",
  "Flowers bloom silently, yet leave the most charming scent in the air.",
  "Your palms seem to hide the secret code of spring.",
  "Every plant here remembers your gentle gaze.",
  "If moonlight fell here, it would be soaked in floral fragrance.",
  "In a noisy world, this small garden is a sanctuary for the soul.",
  "The veins of every leaf are written with the wonders of nature.",
  "You are the creator of this micro-universe, making colors dance.",
  "The halo on the petals is a digital tribute to nature.",
  "Spring never ends here, as long as you keep planting hope.",
  "Stars fall to earth and transform into these colorful beings.",
  "The temperature of your touch is what the flowers crave most.",
  "Every bloom is a miracle across dimensions.",
  "This is your secret forest, hiding the breath of the wind.",
  "If butterflies flew in here, they would get lost in the fragrance.",
  "You create not just a landscape, but a moment of tranquility.",
  "The green here has a healing power to smooth all wrinkles.",
  "The moment a seed lands, a dream is born.",
  "The garden understands every smile of yours.",
  "In these lines and colors, I read the resilience of life.",
  "Morning sun on the flower's heart is nature's gentlest awakening.",
  "Your fingertip magic makes even steel and concrete bloom.",
  "Life here is so light, it feels like it could turn into light at any time.",
  "Every petal carries a whimsical idea about beauty.",
  "May the peace of this garden stay in your heart for a long time.",
  "When the wind blows, the flowers dance in a way only you understand.",
  "Here, new stories sprout quietly every second.",
  "This sea of colors is the most beautiful gift you give to the world.",
  "Look at the budding posture, full of desire for the unknown.",
  "Flowers never wither here because they grow in your love.",
  "Every scent is a digital soul's longing for reality.",
  "In this fantasy space, you are the only colorist.",
  "The fire of life is lit here, reflecting your focused eyes.",
  "This is not just a garden, but a pure land in your heart.",
  "Look, those flowers are trying to grow in your direction.",
  "Every pixel's movement is a tribute to nature's craftsmanship.",
  "The world here is small, but it can hold all your gentleness.",
  "A bloom in a moment is eternity in this sea of code.",
  "You are the guide for this vitality, showing them the world.",
  "May these flowers illuminate every tired moment of yours.",
  "Every sprout is struggling to tell the joy of survival.",
  "The clouds here seem to be tainted with the smell of flowers.",
  "You irrigate with imagination and harvest this brilliance.",
  "In this quiet moment, even the air becomes sweet.",
  "All things have spirits, especially these flowers you planted.",
  "The harmony of colors is the most beautiful melody here.",
  "Every flower has its personality, bold or shy.",
  "Here, time seems to stand still, only vitality flows.",
  "Every touch of yours is a deep caress of the earth.",
  "The scenery here is more moving than a dream.",
  "May your life be as fresh as this garden.",
  "This is the most beautiful encounter between technology and nature.",
  "Every refraction of light crowns your work.",
  "There are countless springs hidden here, waiting for you to discover.",
  "Your creativity makes this void burst into a brilliant rainbow.",
  "Look at the texture of the petals, as if they were within reach.",
  "The vitality here is the warmest miracle in the code world.",
  "Every seed harbors the dream of becoming a forest.",
  "Your focus makes these flowers look their most confident.",
  "You are the only invited guest to this colorful party.",
  "May the fragrance of this garden take away all your worries.",
  "The most beautiful form of life is to bloom freely right now.",
  "Every inch of space here is full of exploratory fun.",
  "You are the guardian of this illusion, watching over every bud.",
  "Every bloom is a profound discussion about beauty.",
  "Under your defined gravity, flowers bloom freely.",
  "There is no severe cold here, only your eternal warm spring.",
  "The posture of every flower is a facet of your personality.",
  "Look, even light and shadow chase the warmth of your fingertips.",
  "Nature here is the crystallization of human wisdom and emotion.",
  "Every fleeting moment deserves to be treated gently.",
  "May this brilliance be the source of your creative inspiration.",
  "You can be anyone here, as long as you are willing to plant.",
  "The breath of flowers is the gentlest background sound here.",
  "Your smile is the best fertilizer for this garden.",
  "See the myriad of colors, all a manifestation of your will.",
  "Every overlay of color achieves a visual feast.",
  "Every drop of dew in this garden reflects your shadow.",
  "May this peace accompany you through every quiet night.",
  "Life here is simple, yet has a breathtaking beauty.",
  "You here draw every circle, it becomes a micro-world.",
  "The low hum of petals is a love song for this era.",
  "Here, we redefine the meaning of 'growth'.",
  "May this garden become an eternal landscape in your heart.",
  "Every curve is a projection of natural rhythm in the digital world.",
  "The fragrance here is invisible, but can penetrate your soul.",
  "Look at that bloom, doesn't it look like your first love?",
  "In this parallel space-time, flowers represent pure hope.",
  "May this brilliance add a touch of color to your ordinary days.",
  "Finally, remember this garden, it is a miracle you created."
];

export const getRandomMessage = (lang: 'CN' | 'EN'): string => {
  const pool = lang === 'CN' ? GARDEN_MESSAGES_CN : GARDEN_MESSAGES_EN;
  return pool[Math.floor(Math.random() * pool.length)];
};

export const analyzeGarden = async (imageBase64: string, flowerCount: number, lang: 'CN' | 'EN' = 'CN'): Promise<string> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(getRandomMessage(lang));
    }, 600);
  });
};
